[images]
  remote_images = [
    "https://ext.same-assets.com/.*",
    "https://images.unsplash.com/.*",
    "https://picsum.photos/.*",
    "https://source.unsplash.com/.*",
    "https://ugc.same-assets.com/.*",
  ]

[build]
  command = "bun run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

